server:
  port: 8002
spring:
  application:
    name: provider-name
  datasource:
    type: com.alibaba.druid.pool.DruidDataSource
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://localhost:3306/springclouddemo2
    username: root
    password: root
  devtools:
    restart:
      enabled: true
eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:7001/eureka/